// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAthdJOHUNGuihH7CsHvK6ig5NSYP-A0Tw',
    appId: '1:673577336633:web:c68a789731595c973cf2e8',
    messagingSenderId: '673577336633',
    projectId: 'greenhouse-management-sy-5e9d4',
    authDomain: 'greenhouse-management-sy-5e9d4.firebaseapp.com',
    storageBucket: 'greenhouse-management-sy-5e9d4.firebasestorage.app',
    measurementId: 'G-1ZFXYNJ3KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpfblVdEWADFE0ajC5NigKUt7WUSC8HI',
    appId: '1:673577336633:android:4faec4d66d76ac0a3cf2e8',
    messagingSenderId: '673577336633',
    projectId: 'greenhouse-management-sy-5e9d4',
    storageBucket: 'greenhouse-management-sy-5e9d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2U1qD5Cm33Js1K59qe2cVpkzUOQkF7rc',
    appId: '1:673577336633:ios:81927ab5fe29b35e3cf2e8',
    messagingSenderId: '673577336633',
    projectId: 'greenhouse-management-sy-5e9d4',
    storageBucket: 'greenhouse-management-sy-5e9d4.firebasestorage.app',
    iosClientId: '673577336633-9ffars3m6h5362dpt88vm45alqhsitp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
